package ru.iandreyshev.gumballmachine.presenter.interfaces

import ru.iandreyshev.gumballmachine.interactor.interfaces.ISettingsInteractor
import ru.iandreyshev.gumballmachine.viewModel.abstractions.AbstractSettingsViewModel

interface ISettingsPresenter : IPresenter<AbstractSettingsViewModel>
